#=======================================
# Configuration File
#=======================================

#=======================================
# Basic configuration
#=======================================
[Basic]

# If tag list is required then set the 
# value to 'Yes' else 'No'
TagListRequired=Yes

#=======================================
# Reader configuration
#=======================================
[Reader]
ReaderIp=10.6.5.35
ReaderPort=20000
ReaderName=GATE READER

#=======================================
# Socket server configuration
#=======================================
[SocketServer]
SocketServerIp=10.6.5.203
SocketServerPort=20000

#=======================================
# KOHA database configuration
#=======================================
[Koha]
ServerIp=Put_the_server_ip
DbPort=3306
DbName=put_the_db_name
DbUid=put_theDb_user_ID
DbPassword=Put_the_db_password